[package]
name = "imghash"
version = "1.2.0"

description = "Image hashing for Rust"

readme = "README.md"
license-file = "LICENSE"

authors = ["Yannick Alexander"]

repository = "https://github.com/YannickAlex07/imghash-rs"

edition = "2021"

[dependencies]
image = { version = "0.24.8", features = ["rayon"] }
rayon = "1.10.0"
