[package]
name = "imghash"
version = "1.5.0"

description = "Image hashing for Rust"

readme = "README.md"
license-file = "LICENSE"

authors = ["Yannick Alexander"]

repository = "https://github.com/YannickAlex07/imghash-rs"

edition = "2021"

[dependencies]
image = { version = "0.25.6", features = ["rayon"] }
bitvec = "1.0.0"
rayon = "1.10.0"
